import re

OGC_CRS84 = "http://www.opengis.net/def/crs/OGC/1.3/CRS84"
IDENTIFIER_RE = re.compile(r"^[a-z][a-z0-9_]*$", re.I)

COLLECTION_ID_MAX_LENGTH = 255
COLLECTION_TITLE_MAX_LENGTH = 255
COLLECTION_DESCRIPTION_MAX_LENGTH = 500
COLLECTION_CRS_MAX_LENGTH = 255
COLLECTION_SCHEMA_NAME_MAX_LENGTH = 64
COLLECTION_TABLE_NAME_MAX_LENGTH = 255
COLLECTION_GEOMETRY_COLUMN_MAX_LENGTH = 64
COLLECTION_ID_COLUMN_MAX_LENGTH = 64
COLLECTION_GEOMETRY_TYPE_MAX_LENGTH = 64
COLLECTION_ERROR_MESSAGE_MAX_LENGTH = 500

DEFAULT_SCHEMA_NAME = "user_data"
DEFAULT_GEOMETRY_COLUMN = "geom"
DEFAULT_ID_COLUMN = "fid"
DEFAULT_SRID = 4326
